export const BUILDINGS_SEED = [
  // ── ACADEMIC ──────────────────────────────────────────────────────────────
  {
    name: 'Lecture Hall Complex',
    shortName: 'LHC',
    type: 'academic',
    floors: 4,
    totalArea: 8000,
    yearBuilt: 1980,
    latitude: 25.2692,
    longitude: 82.992,
    tags: [],
  },
  {
    name: 'Department of Computer Science & Engineering',
    shortName: 'CSE Block',
    type: 'academic',
    floors: 3,
    totalArea: 3000,
    yearBuilt: 1995,
    latitude: 25.268,
    longitude: 82.9935,
    tags: [],
  },
  {
    name: 'Department of Electronics Engineering',
    shortName: 'ECE Block',
    type: 'academic',
    floors: 3,
    totalArea: 2800,
    yearBuilt: 1990,
    latitude: 25.2675,
    longitude: 82.994,
    tags: [],
  },
  {
    name: 'Department of Mechanical Engineering',
    shortName: 'Mech Block',
    type: 'academic',
    floors: 3,
    totalArea: 3200,
    yearBuilt: 1972,
    latitude: 25.2668,
    longitude: 82.993,
    tags: [],
  },
  {
    name: 'Department of Civil Engineering',
    shortName: 'Civil Block',
    type: 'academic',
    floors: 3,
    totalArea: 2500,
    yearBuilt: 1970,
    latitude: 25.266,
    longitude: 82.9925,
    tags: [],
  },
  {
    name: 'Department of Chemical Engineering & Technology',
    shortName: 'Chem Block',
    type: 'academic',
    floors: 3,
    totalArea: 2200,
    yearBuilt: 1975,
    latitude: 25.2665,
    longitude: 82.991,
    tags: [],
  },
  {
    name: 'Department of Physics',
    shortName: 'Physics Block',
    type: 'academic',
    floors: 2,
    totalArea: 1800,
    yearBuilt: 1968,
    latitude: 25.2685,
    longitude: 82.99,
    tags: [],
  },
  {
    name: 'Department of Mathematics',
    shortName: 'Maths Block',
    type: 'academic',
    floors: 2,
    totalArea: 1500,
    yearBuilt: 1968,
    latitude: 25.269,
    longitude: 82.9895,
    tags: [],
  },
  {
    name: 'Department of Humanities & Social Sciences',
    shortName: 'HSS Block',
    type: 'academic',
    floors: 2,
    totalArea: 1200,
    yearBuilt: 1975,
    latitude: 25.2695,
    longitude: 82.9905,
    tags: [],
  },
  {
    name: 'Department of Mining Engineering',
    shortName: 'Mining Block',
    type: 'academic',
    floors: 3,
    totalArea: 2000,
    yearBuilt: 1978,
    latitude: 25.267,
    longitude: 82.995,
    tags: [],
  },
  {
    name: 'Department of Metallurgical Engineering',
    shortName: 'Met Block',
    type: 'academic',
    floors: 3,
    totalArea: 2000,
    yearBuilt: 1978,
    latitude: 25.2672,
    longitude: 82.9945,
    tags: [],
  },
  {
    name: 'Department of Pharmaceutical Engineering',
    shortName: 'Pharma Block',
    type: 'academic',
    floors: 2,
    totalArea: 1500,
    yearBuilt: 2000,
    latitude: 25.2662,
    longitude: 82.9955,
    tags: [],
  },
  {
    name: 'Department of Biochemical Engineering',
    shortName: 'Biochem Block',
    type: 'academic',
    floors: 2,
    totalArea: 1400,
    yearBuilt: 2002,
    latitude: 25.2658,
    longitude: 82.9948,
    tags: [],
  },
  {
    name: 'Department of Architecture & Planning',
    shortName: 'Arch Block',
    type: 'academic',
    floors: 2,
    totalArea: 1600,
    yearBuilt: 1985,
    latitude: 25.2655,
    longitude: 82.9938,
    tags: [],
  },
  {
    name: 'Department of Ceramic Engineering',
    shortName: 'Ceramic Block',
    type: 'academic',
    floors: 2,
    totalArea: 1500,
    yearBuilt: 1980,
    latitude: 25.2652,
    longitude: 82.9928,
    tags: [],
  },
  {
    name: 'Department of Electrical Engineering',
    shortName: 'EE Block',
    type: 'academic',
    floors: 3,
    totalArea: 2200,
    yearBuilt: 1988,
    latitude: 25.2648,
    longitude: 82.9918,
    tags: [],
  },
  {
    name: 'Central Library',
    shortName: 'Library',
    type: 'academic',
    floors: 4,
    totalArea: 5000,
    yearBuilt: 1990,
    latitude: 25.2688,
    longitude: 82.9913,
    tags: [],
  },

  // ── ADMINISTRATIVE ─────────────────────────────────────────────────────────
  {
    name: 'Main Building (Kashinath Hall)',
    shortName: 'Main Building',
    type: 'administrative',
    floors: 3,
    totalArea: 4000,
    yearBuilt: 1919,
    latitude: 25.2677,
    longitude: 82.9913,
    tags: ['heritage'],
  },
  {
    name: 'Institute Office & Administrative Block',
    shortName: 'Admin Block',
    type: 'administrative',
    floors: 2,
    totalArea: 2000,
    yearBuilt: 1970,
    latitude: 25.2678,
    longitude: 82.9908,
    tags: [],
  },
  {
    name: 'IIT BHU Hospital',
    shortName: 'Hospital',
    type: 'administrative',
    floors: 3,
    totalArea: 3500,
    yearBuilt: 1985,
    latitude: 25.27,
    longitude: 82.992,
    tags: [],
  },

  // ── HOSTELS ────────────────────────────────────────────────────────────────
  {
    name: 'Limbdi Hall',
    shortName: 'Limbdi',
    type: 'hostel',
    floors: 3,
    totalArea: 5000,
    yearBuilt: 1960,
    latitude: 25.271,
    longitude: 82.993,
    tags: [],
  },
  {
    name: 'Rajputana Hall',
    shortName: 'Rajputana',
    type: 'hostel',
    floors: 3,
    totalArea: 4500,
    yearBuilt: 1962,
    latitude: 25.2715,
    longitude: 82.9935,
    tags: [],
  },
  {
    name: 'Morvi Hall',
    shortName: 'Morvi',
    type: 'hostel',
    floors: 3,
    totalArea: 4200,
    yearBuilt: 1965,
    latitude: 25.272,
    longitude: 82.9925,
    tags: [],
  },
  {
    name: 'Rampur Hall',
    shortName: 'Rampur',
    type: 'hostel',
    floors: 3,
    totalArea: 3800,
    yearBuilt: 1968,
    latitude: 25.2705,
    longitude: 82.994,
    tags: [],
  },
  {
    name: 'Vivekananda Hall',
    shortName: 'Vivekananda',
    type: 'hostel',
    floors: 4,
    totalArea: 6000,
    yearBuilt: 1975,
    latitude: 25.2712,
    longitude: 82.9945,
    tags: [],
  },
  {
    name: 'Aryabhatta Hall',
    shortName: 'Aryabhatta',
    type: 'hostel',
    floors: 4,
    totalArea: 5500,
    yearBuilt: 1980,
    latitude: 25.2718,
    longitude: 82.995,
    tags: [],
  },
  {
    name: 'CVR Hall (Girls Hostel)',
    shortName: 'CVR Hall',
    type: 'hostel',
    floors: 4,
    totalArea: 5000,
    yearBuilt: 1985,
    latitude: 25.2708,
    longitude: 82.9955,
    tags: [],
  },
  {
    name: 'New Girls Hostel',
    shortName: 'NGH',
    type: 'hostel',
    floors: 4,
    totalArea: 4500,
    yearBuilt: 2005,
    latitude: 25.2703,
    longitude: 82.996,
    tags: [],
  },
  {
    name: 'Ganga Hostel',
    shortName: 'Ganga',
    type: 'hostel',
    floors: 3,
    totalArea: 4000,
    yearBuilt: 1990,
    latitude: 25.2722,
    longitude: 82.9915,
    tags: [],
  },
  {
    name: 'Yamuna Hostel',
    shortName: 'Yamuna',
    type: 'hostel',
    floors: 3,
    totalArea: 3800,
    yearBuilt: 1992,
    latitude: 25.2725,
    longitude: 82.991,
    tags: [],
  },

  // ── LABS & RESEARCH ────────────────────────────────────────────────────────
  {
    name: 'Central Research Facility',
    shortName: 'CRF',
    type: 'lab',
    floors: 2,
    totalArea: 3000,
    yearBuilt: 2010,
    latitude: 25.266,
    longitude: 82.9965,
    tags: [],
  },
  {
    name: 'Advanced Materials Research Lab',
    shortName: 'AMRL',
    type: 'lab',
    floors: 2,
    totalArea: 1500,
    yearBuilt: 2015,
    latitude: 25.2657,
    longitude: 82.997,
    tags: [],
  },
  {
    name: 'Robotics & AI Lab',
    shortName: 'Robotics Lab',
    type: 'lab',
    floors: 1,
    totalArea: 800,
    yearBuilt: 2018,
    latitude: 25.2683,
    longitude: 82.9942,
    tags: [],
  },
  {
    name: 'VLSI Design Lab',
    shortName: 'VLSI Lab',
    type: 'lab',
    floors: 1,
    totalArea: 600,
    yearBuilt: 2012,
    latitude: 25.2679,
    longitude: 82.9947,
    tags: [],
  },

  // ── RESIDENTIAL ────────────────────────────────────────────────────────────
  {
    name: 'Faculty Residences Block A',
    shortName: 'Faculty Block A',
    type: 'residential',
    floors: 3,
    totalArea: 3000,
    yearBuilt: 1980,
    latitude: 25.264,
    longitude: 82.99,
    tags: [],
  },
  {
    name: 'Faculty Residences Block B',
    shortName: 'Faculty Block B',
    type: 'residential',
    floors: 3,
    totalArea: 2800,
    yearBuilt: 1985,
    latitude: 25.2635,
    longitude: 82.9905,
    tags: [],
  },
  {
    name: 'Guest House',
    shortName: 'Guest House',
    type: 'residential',
    floors: 3,
    totalArea: 2000,
    yearBuilt: 1992,
    latitude: 25.2642,
    longitude: 82.9915,
    tags: [],
  },

  // ── INFRASTRUCTURE & COMMERCIAL ────────────────────────────────────────────
  {
    name: 'Sports Complex',
    shortName: 'Sports',
    type: 'infrastructure',
    floors: 1,
    totalArea: 10000,
    yearBuilt: 1995,
    latitude: 25.273,
    longitude: 82.9935,
    tags: [],
  },
  {
    name: 'Central Workshop',
    shortName: 'Workshop',
    type: 'infrastructure',
    floors: 1,
    totalArea: 2000,
    yearBuilt: 1970,
    latitude: 25.2645,
    longitude: 82.996,
    tags: [],
  },
  {
    name: 'Power House',
    shortName: 'Power House',
    type: 'infrastructure',
    floors: 1,
    totalArea: 800,
    yearBuilt: 1965,
    latitude: 25.265,
    longitude: 82.997,
    tags: [],
  },
  {
    name: 'Central Mess A',
    shortName: 'Mess A',
    type: 'commercial',
    floors: 1,
    totalArea: 1500,
    yearBuilt: 1975,
    latitude: 25.2725,
    longitude: 82.992,
    tags: [],
  },
  {
    name: 'Central Mess B',
    shortName: 'Mess B',
    type: 'commercial',
    floors: 1,
    totalArea: 1200,
    yearBuilt: 1980,
    latitude: 25.2728,
    longitude: 82.9925,
    tags: [],
  },
  {
    name: 'Shopping Complex',
    shortName: 'Market',
    type: 'commercial',
    floors: 1,
    totalArea: 800,
    yearBuilt: 1985,
    latitude: 25.2732,
    longitude: 82.9905,
    tags: [],
  },
  {
    name: 'Bank & Post Office Block',
    shortName: 'Bank Block',
    type: 'commercial',
    floors: 1,
    totalArea: 600,
    yearBuilt: 1978,
    latitude: 25.2735,
    longitude: 82.991,
    tags: [],
  },
];
