export type EFSeedEntry = {
  name: string;
  category: string;
  value: number;
  unit: string;
  source: string;
  year: number;
  region: string;
  scope: 'scope1' | 'scope2' | 'scope3' | 'embodied';
  subcategory: string;
  isDefault: boolean;
  isActive: boolean;
};

export const EMISSION_FACTORS_EXTENDED: EFSeedEntry[] = [
  // ── SCOPE 1: FUELS ────────────────────────────────────────────────────────
  {
    name: 'Diesel',
    category: 'diesel',
    value: 2.65,
    unit: 'kgCO2e/litre',
    source: 'IPCC',
    year: 2023,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'fuel',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Petrol',
    category: 'petrol',
    value: 2.31,
    unit: 'kgCO2e/litre',
    source: 'IPCC',
    year: 2023,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'fuel',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'LPG',
    category: 'lpg',
    value: 3.13,
    unit: 'kgCO2e/kg',
    source: 'MoEFCC',
    year: 2023,
    region: 'India',
    scope: 'scope1',
    subcategory: 'fuel',
    isDefault: true,
    isActive: true,
  },

  // ── SCOPE 1: REFRIGERANTS ─────────────────────────────────────────────────
  {
    name: 'Refrigerant R22',
    category: 'refrigerant_r22',
    value: 1960,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Refrigerant R407C',
    category: 'refrigerant_r407c',
    value: 1908,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Refrigerant R134A',
    category: 'refrigerant_r134a',
    value: 1530,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Refrigerant R410A',
    category: 'refrigerant_r410a',
    value: 2256,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Refrigerant R404A',
    category: 'refrigerant_r404a',
    value: 4728,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Refrigerant R32',
    category: 'refrigerant_r32',
    value: 771,
    unit: 'kgCO2e/kg',
    source: 'IPCC AR6',
    year: 2021,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Fire Extinguisher (CO2 leakage)',
    category: 'fire_extinguisher',
    value: 1,
    unit: 'kgCO2e/kg',
    source: 'IIM Ahmedabad',
    year: 2022,
    region: 'India',
    scope: 'scope1',
    subcategory: 'refrigerant',
    isDefault: true,
    isActive: true,
  },

  // ── SCOPE 2: ELECTRICITY ──────────────────────────────────────────────────
  {
    name: 'India Grid Electricity (Annexure 8)',
    category: 'grid_electricity',
    value: 0.82,
    unit: 'kgCO2e/kWh',
    source: 'CEA + MoEFCC',
    year: 2023,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'CEA Grid 2019',
    category: 'grid_electricity',
    value: 0.708,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2019',
    year: 2019,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2020',
    category: 'grid_electricity',
    value: 0.716,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2020',
    year: 2020,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2021',
    category: 'grid_electricity',
    value: 0.716,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2021',
    year: 2021,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2022',
    category: 'grid_electricity',
    value: 0.716,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2022',
    year: 2022,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2023',
    category: 'grid_electricity',
    value: 0.716,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2023',
    year: 2023,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2024',
    category: 'grid_electricity',
    value: 0.82,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2024',
    year: 2024,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'CEA Grid 2025',
    category: 'grid_electricity',
    value: 0.82,
    unit: 'kgCO2e/kWh',
    source: 'CEA CO2 Baseline Database 2025',
    year: 2025,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: false,
    isActive: true,
  },

  // ── SCOPE 3: TRANSPORT & OTHER ────────────────────────────────────────────
  {
    name: 'Employee Commute',
    category: 'employee_commute',
    value: 0.15,
    unit: 'kgCO2e/km',
    source: 'DEFRA',
    year: 2023,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'transport',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Air Travel (Domestic)',
    category: 'air_travel_domestic',
    value: 0.2,
    unit: 'kgCO2e/km',
    source: 'ICAO',
    year: 2023,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'transport',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Office Equipment',
    category: 'office_equipment',
    value: 0.246,
    unit: 'kgCO2e/2022 USD',
    source: 'US EPA / Infosys',
    year: 2022,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'equipment',
    isDefault: true,
    isActive: true,
  },

  // ── EMBODIED CARBON: CONCRETE ─────────────────────────────────────────────
  {
    name: 'PCC M15 Concrete',
    category: 'concrete_pcc',
    value: 329.611,
    unit: 'kgCO2e/m3',
    source: 'GKSPL',
    year: 2022,
    region: 'India',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'RCC M20 Concrete',
    category: 'concrete_rcc',
    value: 381,
    unit: 'kgCO2e/m3',
    source: 'GKSPL',
    year: 2022,
    region: 'India',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },

  // ── EMBODIED CARBON: METALS ───────────────────────────────────────────────
  {
    name: 'Rebar (Steel)',
    category: 'rebar',
    value: 2.6,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Steel Frame',
    category: 'steel_frame',
    value: 3.5,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Steel Section',
    category: 'steel_section',
    value: 2.5,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Aluminum',
    category: 'aluminum',
    value: 26,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },

  // ── EMBODIED CARBON: MASONRY & FINISHES ───────────────────────────────────
  {
    name: 'Brick Masonry',
    category: 'brick',
    value: 0.31,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Ceramic Tile 10mm',
    category: 'ceramic_tile',
    value: 0.68,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Kota Stone 15mm',
    category: 'kota_stone',
    value: 0.056,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Plaster (CS)',
    category: 'plaster',
    value: 0.14,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Paint Double Coat',
    category: 'paint',
    value: 0.73,
    unit: 'kgCO2e/m2',
    source: 'ICE',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Stone Masonry',
    category: 'stone_masonry',
    value: 0.073,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },

  // ── EMBODIED CARBON: WOOD & BOARDS ───────────────────────────────────────
  {
    name: 'Wood Frame',
    category: 'wood',
    value: 2.4,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Plywood Panel',
    category: 'wood_plywood',
    value: -0.31,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Pre-laminated Particle Board',
    category: 'particle_board',
    value: -1.3,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },

  // ── EMBODIED CARBON: CLADDING & PANELS ───────────────────────────────────
  {
    name: 'Glass 6mm',
    category: 'glass',
    value: 21.1,
    unit: 'kgCO2e/m2',
    source: 'EPD Saint Gobain 2023',
    year: 2023,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'uPVC',
    category: 'upvc',
    value: 3.9,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'CGI Sheet',
    category: 'cgi_sheet',
    value: 3,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Gypsum Sheet',
    category: 'gypsum',
    value: 0.26,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Asbestos Sheet',
    category: 'asbestos',
    value: 16.31,
    unit: 'kgCO2e/m2',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Pre-fabricated Puff Panel',
    category: 'puff_panel',
    value: 8.1,
    unit: 'kgCO2e/kg',
    source: 'IFC',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
    isActive: true,
  },

  // ── WASTE ─────────────────────────────────────────────────────────────────
  {
    name: 'Mixed MSW — Unmanaged Dump (India)',
    category: 'solid_waste',
    value: 0.52,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'India',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Organic Waste — Composting',
    category: 'solid_waste_composting',
    value: 0.1,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Dry Waste — Recycling',
    category: 'solid_waste_recycling',
    value: 0.021,
    unit: 'kgCO2e/kg',
    source: 'GHG Protocol Scope 3 Cat.5',
    year: 2022,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Open Burning of Waste',
    category: 'solid_waste_burning',
    value: 0.98,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Wastewater — Unmanaged/Septic',
    category: 'liquid_waste',
    value: 0.068,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'India',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
    isActive: true,
  },
  {
    name: 'Wastewater — Municipal STP',
    category: 'liquid_waste',
    value: 0.012,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: false,
    isActive: true,
  },
  {
    name: 'Wastewater — On-campus Aerobic STP',
    category: 'liquid_waste',
    value: 0.008,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: false,
    isActive: true,
  },
];
