// Legacy seed entries — kept for idempotent re-runs of the main seed script.
// New Annexure 8 factors are seeded via `npm run seed:ef`.
export const EMISSION_FACTORS_SEED = [
  {
    name: 'India Grid Electricity',
    category: 'electricity',
    value: 0.716,
    unit: 'kgCO2e/kWh',
    source: 'CEA 2023',
    year: 2023,
    region: 'India',
    scope: 'scope2',
    subcategory: 'electricity',
    isDefault: true,
  },
  {
    name: 'Diesel',
    category: 'diesel',
    value: 2.68,
    unit: 'kgCO2e/litre',
    source: 'IPCC AR6',
    year: 2022,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'fuel',
    isDefault: true,
  },
  {
    name: 'Petrol',
    category: 'petrol',
    value: 2.31,
    unit: 'kgCO2e/litre',
    source: 'IPCC AR6',
    year: 2022,
    region: 'Global',
    scope: 'scope1',
    subcategory: 'fuel',
    isDefault: true,
  },
  {
    name: 'Steel (production)',
    category: 'steel',
    value: 1.85,
    unit: 'kgCO2e/kg',
    source: 'Worldsteel 2022',
    year: 2022,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: false,
  },
  {
    name: 'Ready-mix concrete',
    category: 'concrete',
    value: 0.159,
    unit: 'kgCO2e/kg',
    source: 'ICE Database v3',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: false,
  },
  {
    name: 'Aluminium (primary)',
    category: 'aluminium',
    value: 8.24,
    unit: 'kgCO2e/kg',
    source: 'ICE Database v3',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: false,
  },
  {
    name: 'Float glass',
    category: 'glass',
    value: 0.91,
    unit: 'kgCO2e/kg',
    source: 'ICE Database v3',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: false,
  },
  {
    name: 'Timber (general)',
    category: 'wood',
    value: 0.72,
    unit: 'kgCO2e/kg',
    source: 'ICE Database v3',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: false,
  },
  {
    name: 'PVC plastic',
    category: 'plastic',
    value: 2.41,
    unit: 'kgCO2e/kg',
    source: 'ICE Database v3',
    year: 2019,
    region: 'Global',
    scope: 'embodied',
    subcategory: 'building_material',
    isDefault: true,
  },

  // SOLID WASTE
  {
    name: 'Mixed MSW — unmanaged dump (India)',
    category: 'solid_waste',
    value: 0.52,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5, India MCF=0.4',
    year: 2006,
    region: 'India',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
  },
  {
    name: 'Organic waste — composting',
    category: 'solid_waste_composting',
    value: 0.1,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5 biological treatment',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
  },
  {
    name: 'Dry waste — recycling',
    category: 'solid_waste_recycling',
    value: 0.021,
    unit: 'kgCO2e/kg',
    source: 'GHG Protocol Scope 3 Cat.5',
    year: 2022,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
  },
  {
    name: 'Open burning of waste',
    category: 'solid_waste_burning',
    value: 0.98,
    unit: 'kgCO2e/kg',
    source: 'IPCC 2006 Vol.5 incineration',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
  },

  // LIQUID WASTE (WASTEWATER)
  {
    name: 'Wastewater — unmanaged/septic',
    category: 'liquid_waste',
    value: 0.068,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5, CH4+N2O combined, EF_CH4=0.6 kgCH4/kgBOD',
    year: 2006,
    region: 'India',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: true,
  },
  {
    name: 'Wastewater — municipal STP',
    category: 'liquid_waste',
    value: 0.012,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5, aerobic treatment',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: false,
  },
  {
    name: 'Wastewater — on-campus aerobic STP',
    category: 'liquid_waste',
    value: 0.008,
    unit: 'kgCO2e/litre',
    source: 'IPCC 2006 Vol.5, best-practice aerobic',
    year: 2006,
    region: 'Global',
    scope: 'scope3',
    subcategory: 'waste',
    isDefault: false,
  },
];
